"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Movie } from "@/lib/media/types";
import { OfflineDownloadButton } from "@/components/media/OfflineDownloadButton";
import { getOfflineDownload, type OfflineDownload } from "@/lib/offline/client";
import type { SkipSegment } from "@/lib/media/skip-segments";

function compatibility(fileName: string) { const extension = fileName.split(".").pop()?.toLowerCase(); if (extension === "mp4" || extension === "m4v") return null; return `.${extension || "unknown"} files may not play in mobile Safari. For reliable mobile playback, use MP4 with H.264 video and AAC audio.`; }

type IOSVideo = HTMLVideoElement & { webkitEnterFullscreen?: () => void; webkitShowPlaybackTargetPicker?: () => void; remote?: { prompt: () => Promise<void> } };

export default function Player({ id }: { id: string }) {
  const router = useRouter(); const videoRef = useRef<HTMLVideoElement>(null); const playerRef = useRef<HTMLDivElement>(null);
  const [movie, setMovie] = useState<Movie | null>(null); const [playbackError, setPlaybackError] = useState(""); const [episodes, setEpisodes] = useState<Movie[]>([]); const [showUpNext, setShowUpNext] = useState(false); const [castAvailable, setCastAvailable] = useState(false); const [offlineDownload, setOfflineDownload] = useState<OfflineDownload | null>(null); const [sourceReady, setSourceReady] = useState(false); const [autoSkip, setAutoSkip] = useState(false); const [skipSegments, setSkipSegments] = useState<SkipSegment[]>([]); const [activeSegment, setActiveSegment] = useState<SkipSegment | null>(null); const autoSkipped = useRef(new Set<string>());
  useEffect(() => { const video = videoRef.current as IOSVideo | null; setCastAvailable(Boolean(video?.webkitShowPlaybackTargetPicker || video?.remote?.prompt)); }, [sourceReady]);
  useEffect(() => { void getOfflineDownload(id).then((download) => { setOfflineDownload(download?.status === "ready" ? download : null); setSourceReady(true); }).catch(() => setSourceReady(true)); fetch(`/api/media/library/${id}`, { cache: "no-store" }).then(async (response) => { const result = await response.json() as { movie?: Movie }; if (response.ok && result.movie) { setMovie(result.movie); if (result.movie.mediaType === "tv") void fetch(`/api/media/skip-segments/${id}`, { cache: "force-cache" }).then((r) => r.json()).then((p: { segments?: SkipSegment[] }) => setSkipSegments(p.segments || [])).catch(() => setSkipSegments([])); if (result.movie.mediaType === "tv") void fetch("/api/media/library", { cache: "no-store" }).then((r) => r.json()).then((library: { movies?: Movie[] }) => setEpisodes((library.movies || []).filter((item) => item.mediaType === "tv" && (item.seriesTitle || item.title).toLowerCase() === (result.movie!.seriesTitle || result.movie!.title).toLowerCase()).sort((a,b)=>(a.seasonNumber||0)-(b.seasonNumber||0)||(a.episodeNumber||0)-(b.episodeNumber||0)))).catch(() => undefined); } }).catch(() => { void getOfflineDownload(id).then((download) => { if (!download) return; setMovie({ id: download.id,title:download.title,year:download.year,fileName:download.fileName,relativePath:"",modifiedAt:download.updatedAt,size:download.size,genre:null,genres:[],isKids:false,mediaType:download.mediaType,seriesTitle:download.seriesTitle,seasonNumber:download.seasonNumber,episodeNumber:download.episodeNumber,overview:null,rating:null,runtimeMinutes:null,tmdbId:null,tagline:null,certification:null,collection:null,posterUrl:null,backdropUrl:null,trailerYouTubeId:null }); }); }); }, [id]);
  useEffect(() => { const initial=window.setTimeout(()=>setAutoSkip(localStorage.getItem("constants-hub-auto-skip")==="true"),0); return()=>window.clearTimeout(initial); },[]); useEffect(()=>{autoSkipped.current.clear();},[id]);
  useEffect(() => { const video=videoRef.current; if(!video)return; let remote=0,lastSync=0; void fetch("/api/user/state",{cache:"no-store"}).then(r=>r.json()).then((state:{progress?:{mediaId:string;seconds:number}[]})=>{remote=state.progress?.find(item=>item.mediaId===id)?.seconds??0;}).catch(()=>undefined); const restore=()=>{const local=Number(localStorage.getItem(`constants-hub-progress:${id}`)||localStorage.getItem(`cmv-progress:${id}`))||0,saved=Math.max(local,remote);if(saved>10&&saved<video.duration-20)video.currentTime=saved;}; const save=(force=false)=>{if(video.currentTime<=0)return;localStorage.setItem(`constants-hub-progress:${id}`,String(video.currentTime));if(force||Date.now()-lastSync>12000){lastSync=Date.now();void fetch("/api/user/state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"progress",mediaId:id,seconds:video.currentTime,duration:video.duration})}).catch(()=>undefined);}}; video.addEventListener("loadedmetadata",restore); const onTimeUpdate=()=>{save(false);const isEpisode=movie?.mediaType==="tv";const segment=isEpisode?skipSegments.find(item=>video.currentTime>=Math.max(0,item.start-3)&&video.currentTime<item.end)||null:null;setActiveSegment(segment);if(segment&&autoSkip&&!autoSkipped.current.has(`${segment.type}:${segment.start}`)){autoSkipped.current.add(`${segment.type}:${segment.start}`);video.currentTime=segment.end;}setShowUpNext(Boolean(isEpisode&&video.duration>0&&video.duration-video.currentTime<=60));}; const onEnded=()=>{save(true);const next=episodes[episodes.findIndex(item=>item.id===id)+1];if(next)router.replace(`/tv/watch/${next.id}`);}; video.addEventListener("timeupdate",onTimeUpdate);video.addEventListener("ended",onEnded);video.focus();return()=>{save(true);video.removeEventListener("loadedmetadata",restore);video.removeEventListener("timeupdate",onTimeUpdate);video.removeEventListener("ended",onEnded);}; },[autoSkip,episodes,id,movie?.mediaType,router,skipSegments,sourceReady]);
  const nextEpisode=useMemo(()=>episodes[episodes.findIndex(item=>item.id===id)+1]||null,[episodes,id]);
  async function cast(){const video=videoRef.current as IOSVideo|null;if(video?.webkitShowPlaybackTargetPicker)video.webkitShowPlaybackTargetPicker();else await video?.remote?.prompt().catch(()=>undefined);}
  async function fullscreen(){const video=videoRef.current as IOSVideo|null;if(!video)return; if(video.webkitEnterFullscreen){video.webkitEnterFullscreen();return;} const target=playerRef.current; if(target?.requestFullscreen){await target.requestFullscreen().catch(()=>undefined);return;} if(video.requestFullscreen) await video.requestFullscreen().catch(()=>undefined);}
  function skip(segment:SkipSegment){const video=videoRef.current;if(video)video.currentTime=segment.end;} function toggleAutoSkip(){setAutoSkip(current=>{const next=!current;localStorage.setItem("constants-hub-auto-skip",String(next));return next;});}
  const warning=movie?compatibility(movie.fileName):null;
  return <main className="player-shell"><Link href={movie?.mediaType==="tv"?`/tv/show/${id}`:`/tv/movie/${id}`} className="player-back">← Back</Link>{castAvailable?<button className="player-cast secondary-button" onClick={()=>void cast()}>▣ Cast</button>:null}{movie?<div className="player-download"><OfflineDownloadButton movie={movie} compact /></div>:null}
    <div ref={playerRef} className="player-video-wrap">{sourceReady?<video ref={videoRef} src={offlineDownload?`/__offline/media/${id}`:`/api/media/stream/${id}`} controls autoPlay playsInline preload="metadata" {...{"x-webkit-airplay":"allow"}} onError={()=>setPlaybackError("This video format or audio codec is not supported by this device.")}><track kind="subtitles" src={`/api/media/subtitles/${id}`} srcLang="en" label="English" /></video>:<div className="player-loading">Preparing player…</div>}<button type="button" className="player-fullscreen-button" aria-label="Enter full screen" onClick={()=>void fullscreen()}>⛶</button></div>
    {offlineDownload?<span className="player-offline-badge">✓ Playing offline copy</span>:null}{movie?.mediaType==="tv"?<div className="skip-controls">{activeSegment?<button className="skip-button" onClick={()=>skip(activeSegment)}>Skip {activeSegment.type==="recap"?"Recap":"Intro"}<span>to {Math.floor(activeSegment.end/60)}:{String(Math.floor(activeSegment.end%60)).padStart(2,"0")}</span></button>:null}{skipSegments.length?<button className={`auto-skip-button${autoSkip?" active":""}`} aria-pressed={autoSkip} onClick={toggleAutoSkip}>{autoSkip?"✓ Auto-skip detected segments":"Auto-skip off"}</button>:null}</div>:null}{showUpNext&&nextEpisode?<aside className="up-next"><small>UP NEXT</small><strong>{nextEpisode.title}</strong><div><button className="primary-button" onClick={()=>router.replace(`/tv/watch/${nextEpisode.id}`)}>Play now</button><button className="secondary-button" onClick={()=>setShowUpNext(false)}>Dismiss</button></div></aside>:null}{warning||playbackError?<aside className="player-notice" role="alert"><strong>{playbackError?"Playback unavailable":"Mobile compatibility"}</strong><p>{playbackError||warning}</p><small>Original file: {movie?.fileName||"Loading…"}</small></aside>:null}</main>;
}
