"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Health = { status: "ok" | "degraded"; media: "available" | "unavailable"; tmdbConfigured: boolean };
type Dashboard = { movies: number; shows: number; episodes: number; storageBytes: number; missingPosters: number; recentlyAdded: string[]; conversions: { queued: number; failed: number; completed: number }; streaming: boolean; conversionWindowOpen: boolean; alerts: { level: "warning" | "error"; title: string; action: string }[] };
type PcWorker = { success: boolean; enabled?: boolean; status?: { status?: string; reason?: string; source?: string; mode?: string; updatedAt?: string; computer?: string; override?: boolean } | null; error?: string };

export default function SettingsPage() {
  const [health, setHealth] = useState<Health | null>(null); const [movieCount, setMovieCount] = useState<number | null>(null); const [lastScan, setLastScan] = useState<string | null>(null); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false); const [syncingPosters, setSyncingPosters] = useState(false); const [posterMessage, setPosterMessage] = useState(""); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [owner, setOwner] = useState(false); const [pcWorker, setPcWorker] = useState<PcWorker | null>(null); const [pcBusy, setPcBusy] = useState(false); const [pcMessage, setPcMessage] = useState("");
  async function refresh() { setRefreshing(true); setError(""); try { const [healthResponse,libraryResponse,dashboardResponse,sessionResponse,pcResponse]=await Promise.all([fetch("/api/health",{cache:"no-store"}),fetch("/api/media/library",{cache:"no-store"}),fetch("/api/admin/dashboard",{cache:"no-store"}),fetch("/api/auth/me",{cache:"no-store"}),fetch("/api/admin/pc-worker",{cache:"no-store"})]); const healthResult=await healthResponse.json() as Health; const libraryResult=await libraryResponse.json() as {success:boolean;movieCount?:number;scannedAt?:string;error?:string}; setHealth(healthResult); if(dashboardResponse.ok)setDashboard(await dashboardResponse.json() as Dashboard); if(sessionResponse.ok){const session=await sessionResponse.json() as {profile?:{role?:string}|null};setOwner(session.profile?.role==="owner")}; if(pcResponse.ok)setPcWorker(await pcResponse.json() as PcWorker); if(!libraryResponse.ok||!libraryResult.success)throw new Error(libraryResult.error||"Library scan failed."); setMovieCount(libraryResult.movieCount??0);setLastScan(libraryResult.scannedAt??null)}catch(reason){setError(reason instanceof Error?reason.message:"System check failed.")}finally{setRefreshing(false)} }
  async function refreshPcWorker(){try{const response=await fetch("/api/admin/pc-worker",{cache:"no-store"});if(response.ok)setPcWorker(await response.json() as PcWorker)}catch{}}
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);const interval=window.setInterval(()=>void refreshPcWorker(),3000);return()=>{window.clearTimeout(timer);window.clearInterval(interval)}},[]);
  async function pcCommand(action:"enable"|"run-now"|"pause"|"resume"|"stop"){setPcBusy(true);setPcMessage("");setError("");try{const response=await fetch("/api/admin/pc-worker",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const result=await response.json() as PcWorker;if(!response.ok||!result.success)throw new Error(result.error||"PC worker command failed.");setPcWorker(result);setPcMessage(action==="run-now"?"Convert Now sent to CAZ-PC.":action==="enable"?"PC worker enabled; NAS conversion disabled.":`PC worker ${action} command sent.`);window.setTimeout(()=>void refreshPcWorker(),1000)}catch(reason){setError(reason instanceof Error?reason.message:"PC worker command failed.")}finally{setPcBusy(false)}}
  async function syncPosters(){setSyncingPosters(true);setPosterMessage("");setError("");try{const response=await fetch("/api/media/artwork/sync",{method:"POST"});const result=await response.json() as {success:boolean;message?:string;error?:string};if(!response.ok||!result.success)throw new Error(result.error||"Poster sync failed.");setPosterMessage(result.message||"Poster sync completed.")}catch(reason){setError(reason instanceof Error?reason.message:"Poster sync failed.")}finally{setSyncingPosters(false)}}
  async function restoreBackup(file:File|undefined){if(!file||!window.confirm("Restore profiles, progress, and watchlists from this backup?"))return;setError("");try{const response=await fetch("/api/admin/backup",{method:"POST",headers:{"Content-Type":"application/json"},body:await file.text()});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Restore failed.");window.alert("Backup restored. Existing logins may need to sign in again.")}catch(reason){setError(reason instanceof Error?reason.message:"Restore failed.")}}
  const workerState=pcWorker?.status?.status||"Offline / waiting for PC";
  return <main className="admin-shell"><header className="admin-header"><div><Link href="/tv">← TV Mode</Link><p className="eyebrow">CONSTANT’S HUB</p><h1>System Status</h1></div><button className="primary-button" onClick={()=>void refresh()} disabled={refreshing}>{refreshing?"Checking…":"Refresh"}</button></header>
    {error?<div className="state-card error">{error}</div>:null}
    {dashboard?.alerts?.length?<section className="admin-panel"><p className="eyebrow">NOTIFICATIONS</p><h2>Needs attention</h2>{dashboard.alerts.map(alert=><p key={`${alert.action}-${alert.title}`}><Link href={alert.action}>{alert.title} →</Link></p>)}</section>:null}
    <section className="status-grid"><StatusCard label="Synology NAS" title="Media Storage" state={health?.media==="available"?"Connected":health?"Unavailable":"Checking"} good={health?.media==="available"}><p>The configured MEDIA_ROOT is checked directly by the server.</p></StatusCard><StatusCard label="Movie Metadata" title="TMDB" state={health?.tmdbConfigured?"Configured":health?"Optional":"Checking"} good={Boolean(health?.tmdbConfigured)}><p>Metadata enriches the catalog when available; local titles and artwork remain the fallback.</p></StatusCard><StatusCard label="Library" title="Movies Ready" state={movieCount===null?"Checking":String(movieCount)} good={movieCount!==null}><p>{lastScan?`Last scanned ${new Date(lastScan).toLocaleString()}.`:"Waiting for the first scan."}</p></StatusCard><StatusCard label="Playback" title="Secure Streaming" state="Ready" good><p>ID-based streaming supports byte ranges, seeking, and Resume playback.</p></StatusCard></section>
    <section className="admin-panel"><p className="eyebrow">PC CONVERSION WORKER</p><h2>RTX Conversion Control</h2><p>Use the gaming PC for fast H.264/AAC compatibility work. Convert Now bypasses the overnight schedule, but the GPU-busy guard still protects gaming.</p><p><strong>Status:</strong> {workerState}{pcWorker?.status?.reason?` — ${pcWorker.status.reason}`:""}{pcWorker?.status?.computer?` (${pcWorker.status.computer})`:""}</p>{pcWorker?.status?.source?<p><strong>Current:</strong> {pcWorker.status.source.split("\\").pop()}{pcWorker.status.mode?` · ${pcWorker.status.mode}`:""}</p>:null}<div className="hero-actions">{!pcWorker?.enabled?<button className="secondary-button" disabled={pcBusy} onClick={()=>void pcCommand("enable")}>Enable PC Worker</button>:null}<button className="primary-button" disabled={pcBusy||!pcWorker?.enabled} onClick={()=>void pcCommand("run-now")}>Convert Now</button><button className="secondary-button" disabled={pcBusy||!pcWorker?.enabled} onClick={()=>void pcCommand("pause")}>Pause</button><button className="secondary-button" disabled={pcBusy||!pcWorker?.enabled} onClick={()=>void pcCommand("resume")}>Resume</button></div>{pcMessage?<p className="artwork-ready">{pcMessage}</p>:null}</section>
    {dashboard?<section className="admin-panel"><p className="eyebrow">LIBRARY DASHBOARD</p><h2>At a glance</h2><div className="metric-grid"><div><strong>{dashboard.movies}</strong><span>Movies</span></div><div><strong>{dashboard.shows}</strong><span>Shows</span></div><div><strong>{dashboard.episodes}</strong><span>Episodes</span></div><div><strong>{(dashboard.storageBytes/1073741824).toFixed(1)} GB</strong><span>Media storage</span></div><div><strong>{dashboard.missingPosters}</strong><span>Missing posters</span></div><div><strong>{dashboard.conversions.failed}</strong><span>Failed conversions</span></div></div><p>{dashboard.streaming?"Streaming detected.":dashboard.conversionWindowOpen?"Overnight PC conversion window is open.":"PC conversions are waiting for the overnight window or Convert Now."}</p>{dashboard.recentlyAdded.length?<p><strong>Recently added:</strong> {dashboard.recentlyAdded.join(", ")}</p>:null}</section>:null}
    {owner?<section className="admin-panel"><p className="eyebrow">OWNER ACCESS</p><h2>Household Profiles</h2><p>Create Admin, Family, Kids, and expiring Guest accounts. Only the Owner can manage accounts and passwords.</p><Link className="secondary-button" href="/settings/profiles">Manage Profiles</Link></section>:<section className="admin-panel"><p className="eyebrow">ADMIN ACCESS</p><h2>Media administration</h2><p>You can manage the library, organizer, artwork, collections, and conversions. Account management and backups remain Owner-only.</p></section>}
    <section className="admin-panel"><p className="eyebrow">MEDIA TOOLS</p><h2>Compatibility & Organizer</h2><p>Inspect real codecs, convert incompatible movies for mobile playback, organize Inbox files, and manage household categories.</p><div className="hero-actions"><Link className="secondary-button" href="/settings/media">Media Compatibility</Link><Link className="secondary-button" href="/organize">Open Organizer</Link><Link className="secondary-button" href="/settings/categories">Kids Categories</Link><Link className="secondary-button" href="/settings/collections">Custom Collections</Link></div></section>
    <section id="posters" className="admin-panel"><p className="eyebrow">SAMSUNG TV ARTWORK</p><h2>Sync Missing Posters</h2><p>Downloads missing TMDB artwork as both poster.jpg and folder.jpg beside each movie. Synology Media Server still needs to re-index before its DLNA thumbnails update.</p><button className="secondary-button" disabled={syncingPosters} onClick={()=>void syncPosters()}>{syncingPosters?"Syncing…":"Sync Missing Posters"}</button>{posterMessage?<p className="artwork-ready">{posterMessage}</p>:null}</section>
    {owner?<section className="admin-panel"><p className="eyebrow">BACKUP & RECOVERY</p><h2>Protect household data</h2><p>Export profiles, password hashes, viewing progress, watchlists, a library snapshot, and non-secret conversion settings. Media files and environment secrets are never included.</p><div className="hero-actions"><a className="secondary-button" href="/api/admin/backup" download>Export Backup</a><label className="secondary-button">Restore Backup<input hidden type="file" accept="application/json,.json" onChange={event=>void restoreBackup(event.target.files?.[0])}/></label></div></section>:null}
  </main>;
}
function StatusCard({label,title,state,good,children}:{label:string;title:string;state:string;good:boolean;children:React.ReactNode}){return <article className="status-card"><div className="status-card-top"><div><small>{label}</small><h2>{title}</h2></div><span className={good?"status-good":"status-neutral"}>{state}</span></div>{children}</article>}
